### ISSUE TITLE
tiny mistake on  Stabilize.cpp.

### ISSUE THREAD

**Issue by estevaofv** [ivanseidel/EasyFly#1]
I think you made a very small mistake on the file Stabilize.cpp. I think it is just a typo, I think that instead of && should be || since you are verifying if the delta time is too small or too high before you calculate the PID. 

line 93:    if(dt <= 0.0 && dt >= 0.2){

should be: if(dt <= 0.0 || dt >= 0.2){

BTW great video and code!

**Comment by ivanseidel** [comment]
Ops! Didn't notice that..
Do you want to commit and create a pull request?

Thanks!

**Comment by estevaofv** [comment]
well I'm not sure how to do that hahahah I' just started learning how git works hahah this is my first time reporting an issue, Actually I'm not sure if I should have created a new Issue for a problem so small hahhaha

**Comment by ivanseidel** [comment]
so, be welcome to learn and contribute ;)

If you learned it right, I will see a pull request later today :smiley: 

(If you don't want to, I can fix it, but I prefer you doing, so that credits go to you)

**Comment by estevaofv** [comment]
Alright! Challenge accepted hahahh! I will try! thanks!
